package com.qf.domain;

import lombok.ToString;

@ToString
public class Deduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deduct.property_fee
     *
     * @mbg.generated
     */
    private Double propertyFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deduct.hot_fee
     *
     * @mbg.generated
     */
    private Double hotFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deduct.deduct_time
     *
     * @mbg.generated
     */
    private Integer deductTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deduct.warn_time
     *
     * @mbg.generated
     */
    private Integer warnTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deduct
     *
     * @mbg.generated
     */
    public Deduct(Double propertyFee, Double hotFee, Integer deductTime, Integer warnTime) {
        this.propertyFee = propertyFee;
        this.hotFee = hotFee;
        this.deductTime = deductTime;
        this.warnTime = warnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deduct
     *
     * @mbg.generated
     */
    public Deduct() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deduct.property_fee
     *
     * @return the value of deduct.property_fee
     *
     * @mbg.generated
     */
    public Double getPropertyFee() {
        return propertyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deduct.property_fee
     *
     * @param propertyFee the value for deduct.property_fee
     *
     * @mbg.generated
     */
    public void setPropertyFee(Double propertyFee) {
        this.propertyFee = propertyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deduct.hot_fee
     *
     * @return the value of deduct.hot_fee
     *
     * @mbg.generated
     */
    public Double getHotFee() {
        return hotFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deduct.hot_fee
     *
     * @param hotFee the value for deduct.hot_fee
     *
     * @mbg.generated
     */
    public void setHotFee(Double hotFee) {
        this.hotFee = hotFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deduct.deduct_time
     *
     * @return the value of deduct.deduct_time
     *
     * @mbg.generated
     */
    public Integer getDeductTime() {
        return deductTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deduct.deduct_time
     *
     * @param deductTime the value for deduct.deduct_time
     *
     * @mbg.generated
     */
    public void setDeductTime(Integer deductTime) {
        this.deductTime = deductTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deduct.warn_time
     *
     * @return the value of deduct.warn_time
     *
     * @mbg.generated
     */
    public Integer getWarnTime() {
        return warnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deduct.warn_time
     *
     * @param warnTime the value for deduct.warn_time
     *
     * @mbg.generated
     */
    public void setWarnTime(Integer warnTime) {
        this.warnTime = warnTime;
    }
}