package com.qf.domain;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.per_id
     *
     * @mbg.generated
     */
    private Integer perId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.per_name
     *
     * @mbg.generated
     */
    private String perName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.per_deso
     *
     * @mbg.generated
     */
    private String perDeso;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated
     */
    public Permission(Integer perId, String perName, String perDeso) {
        this.perId = perId;
        this.perName = perName;
        this.perDeso = perDeso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated
     */
    public Permission() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.per_id
     *
     * @return the value of permission.per_id
     *
     * @mbg.generated
     */
    public Integer getPerId() {
        return perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.per_id
     *
     * @param perId the value for permission.per_id
     *
     * @mbg.generated
     */
    public void setPerId(Integer perId) {
        this.perId = perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.per_name
     *
     * @return the value of permission.per_name
     *
     * @mbg.generated
     */
    public String getPerName() {
        return perName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.per_name
     *
     * @param perName the value for permission.per_name
     *
     * @mbg.generated
     */
    public void setPerName(String perName) {
        this.perName = perName == null ? null : perName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.per_deso
     *
     * @return the value of permission.per_deso
     *
     * @mbg.generated
     */
    public String getPerDeso() {
        return perDeso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.per_deso
     *
     * @param perDeso the value for permission.per_deso
     *
     * @mbg.generated
     */
    public void setPerDeso(String perDeso) {
        this.perDeso = perDeso == null ? null : perDeso.trim();
    }
}