package com.qf.domain;

import lombok.ToString;

@ToString
public class StaffRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_role.staff_role_id
     *
     * @mbg.generated
     */
    private Integer staffRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_role.staff_id
     *
     * @mbg.generated
     */
    private Integer staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_role.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     *
     * @mbg.generated
     */
    public StaffRole(Integer staffRoleId, Integer staffId, Integer roleId) {
        this.staffRoleId = staffRoleId;
        this.staffId = staffId;
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     *
     * @mbg.generated
     */
    public StaffRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_role.staff_role_id
     *
     * @return the value of staff_role.staff_role_id
     *
     * @mbg.generated
     */
    public Integer getStaffRoleId() {
        return staffRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_role.staff_role_id
     *
     * @param staffRoleId the value for staff_role.staff_role_id
     *
     * @mbg.generated
     */
    public void setStaffRoleId(Integer staffRoleId) {
        this.staffRoleId = staffRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_role.staff_id
     *
     * @return the value of staff_role.staff_id
     *
     * @mbg.generated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_role.staff_id
     *
     * @param staffId the value for staff_role.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_role.role_id
     *
     * @return the value of staff_role.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_role.role_id
     *
     * @param roleId the value for staff_role.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}