package com.qf.dao;

import com.qf.domain.Deduct;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DeductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deduct
     *
     * @mbg.generated
     */
    int insert(Deduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deduct
     *
     * @mbg.generated
     */
    int insertSelective(Deduct record);

    Deduct getDeduct();

    int updateDeduct(Deduct deduct);
}