package com.qf.dao;

import com.qf.bean.PageBean;
import com.qf.bean.StaffAndRole;
import com.qf.domain.StaffRole;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface StaffRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer staffRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     *
     * @mbg.generated
     */
    int insert(StaffRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     *
     * @mbg.generated
     */
    int insertSelective(StaffRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     *
     * @mbg.generated
     */
    StaffRole selectByPrimaryKey(Integer staffRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StaffRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StaffRole record);

    List<StaffAndRole> findStaff(PageBean pageBean);
    Long findStaffCount(PageBean pageBean);

    Integer updateRole(StaffRole staffRole);
}