package com.qf.dao;

import com.qf.domain.StaffRole;

public interface StaffRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer staffRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     *
     * @mbg.generated
     */
    int insert(StaffRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     *
     * @mbg.generated
     */
    int insertSelective(StaffRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     *
     * @mbg.generated
     */
    StaffRole selectByPrimaryKey(Integer staffRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StaffRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StaffRole record);
}